In [394]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [408]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/KHUTHON/urls.csv", index_col = 0)
df.head()

Title                                          thumbnail  \
0      Hadoop Yarn 아키텍쳐  https://velog.velcdn.com/images/matteblack9/po...   
1  하둡 프로그래밍 - MapReduce  https://velog.velcdn.com/images%2Fspdlqjfire%2...   
2  OpenSearch에 대해 알아보자!  https://velog.velcdn.com/images/sosimina/post/...   
3          {일상} 10분만 일상  https://velog.velcdn.com/images/pairkorean/pro...   
4               Airflow  https://images.velog.io/images/ifelifelse/post...   

                                                text  
0  개발Hadoop을 배우게 되면, MapReduce 다음으로 Yarn의 개념을 가장 ...  
1  하둡하둡은 기본적으로 HDFS, MapReduce로 구성된다. 맵리듀스는 HDFS에...  
2  Opensearch는 Elastic Search가 기업화를 꾀하는데에 대한 반발로 ...  
3  {일상}10분동안 할게 뭐 있다고, 아둥바둥 힘들게 기록하나 싶다가도나한테 올바른 ...  
4  강의정리 - MLOps목차\nApache Airflow 소개\n-- Batch Pr...

## **문서 전처리**

불용어 제거

In [409]:
! pip install konlpy
! pip install nltk
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [410]:
# 한국어 stopwords
file_path = '/content/drive/MyDrive/KHUTHON/stopword.txt'
text_list = []
with open(file_path, 'r', encoding='utf-8') as file:
    text_list = file.readlines()
cleaned_list = [word.strip() for word in text_list]

# 영어 stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
eng_stopword = stopwords.words('english')

# 특수문자 stopwords
special_characters = list("~!@#$%^&*()_-+=[]{}|;':,.<>?/''")

# 한국어 조사 리스트
korean_particles = [
    '\n',
    '이', '가', '은', '는', '을', '를', '과', '와', '으로', '로', '에', '에서', '의', '에게', '에게서', '랑', '이랑', '처럼', '에서는',
    '에는', '와는', '한테', '에서는', '부터', '까지', '에도', '에만', '에서만', '조차', '마저', '에서부터', '으로부터', '로부터', '으로서', '로서',
    '에너', '같이', '만큼', '따라', '에게서', '보다', '같아서', '처럼', '같다', '같이', '만큼', '보다', '죠', '잖아', '라고', '라는', '이라고', '이라는',
]

# 불용어 제거 리스트
stop_words = cleaned_list + eng_stopword + special_characters + korean_particles

# 숫자 지우기
def remove_numbers(sentence):
    result = ''.join(char for char in sentence if not char.isnumeric())
    return result

# Okt(Open Korea Text) 토크나이저
from konlpy.tag import Okt
okt=Okt()

result = []
for txt in df['text']:
  txt = remove_numbers(txt)
  word_tokens = okt.morphs(txt)
  embedded = []
  for w in word_tokens:
    if w not in stop_words:
        embedded.append(w)
  result.append(' '.join(embedded))

result[0]

'개발 Hadoop 배우게 되면 MapReduce Yarn 개념 가장 많이 접 하게 되는데 대부분 단순히 리소스 매니저 단어 정도 로만 머릿속 넣고 지나간다 문제 해결 하는 데 있어서 문제 본질 핵심 대해 깊이 알 지 못 하면 그것 해결 하지 못 한다는 믿음 근거 하여 정리 남기고자 한다 먼저 Yarn Hadoop 나오게 된 배경 살펴보자 Hadoop Hadoop Data Processing 부분 Resource Management 부분 Layer 관리 해왔 음 알 수 있는데 이를 더 자세히 말 하자면 Job Tracker Task Tracker 두 개 구성 요소 생각 하면 되겠다 Job Tracker 클러스터 현재 resource 가용 한지 모니터링 하는 리소스 관리 기능 수행 하고 MapReduce 잡 스케줄링 하고 배포 하고 모니터링 하는 실행 관리 기능 수행 한다 Task Tracker Job Tracker 수행 될 Task ID 받아와 Task Processing 현황 Job Tracker 보고 하는 제한 적 인 기능 만을 수행 한다 Job Tracker Name Node NN 상 수행 되는 데 클러스터 단 name node hadoop 구조 상 모든 클러스터 노드 관리 하는 구조 되어있어 single point failure 문제점 클러스터 관리자 자체 적 stand node 활성화 하도록 해야 한다 Hadoop 경우 Job Tracker 약 개 노드 개 태스크 까지만 관리 할 수 있다고 알려져있다 Hadoop 하둡 부터는 많은 부족한 부분 보완 되었다 크게 가지 보면 되는데 Job Tracker 담당 했던 클러스터 리소스 관리 실행 관리 부분 여러 개 컴포넌트 나누어 클러스터 더 많은 노드 태스크 관리 할 수 있도록 하였다 MapReduce 모델 뿐 아니라 Spark HBase Storm 데이터 처리 모델 지원 하게 되었다 Application Master 특정한 어플리케이션 처리 라이브러리 올림으로써 하둡 클러스터 다양한 어플리케이션 돌아가는 가

In [411]:
result[1]

'하둡 하둡 기본 적 HDFS MapReduce 구성 된다 맵리듀스 HDFS 저장 된 파일 분산 배치 분석 할 수 있게 도와주는 프레임 워 크이다 개발자 맵리듀스 프로그래밍 모델 맞게 애플리케이션 구현 한 다 데이터 전송 분산 처리 내 고장 성 복잡한 처리 맵리듀스 프레임워크 자동 담당 하는 Runtime System .. MapReduce 개념 맵리듀스 프로그래밍 모델 Map Reduce 크게 가지 단계 데이터 처리 한다 맵 입력 파일 한 줄 씩 읽어 데이터 변형 Transformation 하며 리 듀스 맵 결과 데이터 집계 Aggregation 한다 개발자 맵 데이터 Transformation 규칙 자유롭게 구현 하여 정의 할 수 맵리듀스 프로그래밍 모델 함수 표현 할 수 맵 key value => list key value 리 듀스 key list value )) => key list value )). MapReduce Architecture 맵리듀스 프레임워크 Runtime System 개발자 단순하게 분석 로직 구현 하고 데이터 대한 분산 병렬 처리 대한 어려운 문제 프레임워크 전담 한다 그렇기에 개발자 맵리듀스 아키텍처 몰라도 개발 가능하다 아키텍처 제대로 알 지 못 한 채 개발 하게 되면 성능 고려 하지 않게 되므로 이는 바람직하지 맵리듀스 시스템 JobTracker TaskTracker 구성 되며 HDFS 마찬가지 master slaves 구조 클라이언트 JobTracker Job 실행 요청 하고 Job 진행 상황 완료 결과 공유 받게 된다 클라이언트 란 사용자 실행 한 맵리듀스 프로그램 하둡 제공 하는 맵리듀스 API 말 한다 클라이언트 란 사용자 실행 한 맵리듀스 프로그램 하둡 제공 하는 맵리듀스 API 말 한다 클라이언트 실행 요청 하는 맵리듀스 프로그램 Job 하는 단위 관리 된다 Job 여러 개 task 들로 분산 되어 처리 된다 Job Tracker 하둡 클러스터 있는 전체 Job 스케줄링 관리 하며 모니터링 한다 전체 하둡 클러스터 

## **TF-IDF 벡터화**

In [413]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidfv = TfidfVectorizer().fit(result)
doc_vec = tfidfv.transform(result).toarray()
print(doc_vec)
print(tfidfv.vocabulary_)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.05228485 0.        ]]
{'개발': 991, 'hadoop': 310, '배우게': 1754, '되면': 1423, 'mapreduce': 447, 'yarn': 899, '개념': 990, '가장': 935, '많이': 1602, '하게': 2993, '되는데': 1417, '대부분': 1350, '단순히': 1322, '리소스': 1551, '매니저': 1611, '단어': 1323, '정도': 2649, '로만': 1543, '머릿속': 1622, '넣고': 1263, '지나간다': 2743, '문제': 1679, '해결': 3068, '하는': 3005, '있어서': 2537, '본질': 1833, '핵심': 3103, '대해': 1363, '깊이': 1173, '하면': 3026, '그것': 1103, '하지': 3036, '한다는': 3046, '믿음': 1691, '근거': 1123, '하여': 3030, '정리': 2651, '남기고자': 1231, '한다': 3044, '먼저': 1624, '나오게': 1213, '배경': 1750, '살펴보자': 1927, 'data': 173, 'pr

In [414]:
doc_vec.shape

(23, 3172)

## **가중치 계산**

In [428]:
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

from itertools import combinations, permutations
perm = list(combinations(range(len(df)), 2))

weight_dict = {
    'doc1' : [],
    'doc2' : [],
    'weight' : []
}

for p in perm:
  weight_dict['doc1'].append(p[0])
  weight_dict['doc2'].append(p[1])
  weight_dict['weight'].append(cos_sim(doc_vec[p[0]], doc_vec[p[1]]))

weight_df = pd.DataFrame(weight_dict)
weight_df = weight_df.sort_values(by='weight')
weight_df

doc1  doc2    weight
43      2     3  0.000000
64      3     5  0.001137
67      3     8  0.001358
78      3    19  0.001824
69      3    10  0.002417
..    ...   ...       ...
27      1     7  0.230120
234    16    19  0.236055
0       0     1  0.328395
232    16    17  0.491768
240    17    20  0.643688

[253 rows x 3 columns]

from matplotlib import pyplot as plt
weight_df['doc1'].plot(kind='hist', bins=20, title='doc1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
weight_df['doc2'].plot(kind='hist', bins=20, title='doc2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
weight_df['weight'].plot(kind='hist', bins=20, title='weight')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
weight_df.plot(kind='scatter', x='doc1', y='doc2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
weight_df.plot(kind='scatter', x='doc2', y='weight', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['weight']
  ys = series['doc1']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = weight_df.sort_values('weight', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('weight')
_ = plt.ylabel('doc1')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['weight']
  ys = series['doc2']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = weight_df.sort_values('weight', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('weight')
_ = plt.ylabel('doc2')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['weight']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'weight'}, axis=1)
              .sort_values('weight', ascending=True))
  xs = counted['weight']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = weight_df.sort_values('weight', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('weight')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
weight_df['doc1'].plot(kind='line', figsize=(8, 4), title='doc1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
weight_df['doc2'].plot(kind='line', figsize=(8, 4), title='doc2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
weight_df['weight'].plot(kind='line', figsize=(8, 4), title='weight')
plt.gca().spines[['top', 'right']].set_visible(False)

In [416]:
weight_df.to_csv('weight.csv', index=False)

## **2차원 차원축소**

In [417]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(doc_vec)
df_pca = pca.transform(doc_vec)
print(df_pca.shape)

(23, 2)


## **NEO K-means**

In [429]:
C = [[1, 0],
     [0, 0.7],
     [3, 2],
]
k = len(C)
C = np.array(C) # k는 클러스터 개수, m은 각 중심점의 좌표
alpha_delta = 1.1
beta_delta = 6

def estimate_alpha_beta(X, C, alpha_delta, beta_delta): # X(n*m), C(k*m) : 행렬 /  delta :상수 값
  n = X.shape[0]        # 데이터 개수
  k = C.shape[0]        # centroid 수
  U = np.zeros((n, k))  # 행렬 U 생성 *distnace 저장

  # 거리 계산
  for j in range(k):                              # 모든 (i,j)에 대해 거리가 게산되어 행렬 U 완성
    diff = X - np.tile(C[j, :], (n, 1))           # 센트로이드 c_j의 좌표 C[j, :]가 (n,1)차원만큼 반복하여 쌓는다. -> 모든 데이터 좌표와 거리 계산
    U[:, j] = np.sqrt(np.sum(diff**2, axis=1))    # 유클리디안 거리 행렬에 삽입

  dist = np.min(U, axis=1)      # 각 행(데이터)별로 가장 가까운 클러스터 중심과의 거리를 가져와서 dist 배열에 저장 / (N, 1) 형태의 2차원 배열
  ind = np.argmin(U, axis=1)    # 각 행(데이터)별로 가장 가까운 클러스터의 인덱스를 가져와서 ind 배열에 저장 / (N, 1) 형태의 2차원 배열

  # beta 추정
  betaN = np.count_nonzero(dist > (np.mean(dist) + beta_delta * np.std(dist)))  # 이상치로 간주되는 데이터 개수
  beta = betaN / n    # 이상치 개수 / 전체 데이터 개수

  # alpha 추정 - 겹치는 부분이 작은 경우일 때의 임계치를 기준으로 추정
  overlap = 0     # 겸치는 개수

  for j in range(k) :
    if np.count_nonzero(ind == j) > 0:    # 클러스터에 할당되어 있다면,
      cdist = dist[ind == j]              # 중심과 클러스터에 속한 인스턴스들 사이의 거리만 가져오기
      threshold = np.mean(cdist) + alpha_delta * np.std(cdist)
      v = (U[ind != j, j] <= threshold)   # 클러스터 j에 속하지 않는 임의의 인스턴스 v와 클러스터 J 사이의 거리 < 임계치 -> True -> v는 overlapped region에 위치한 것으로 간주
      overlap += np.count_nonzero(v)

  alpha = overlap / n    # 겹치는 개수 / 전체 데이터 개수
  return alpha, beta

alpha, beta = estimate_alpha_beta(df_pca, C, alpha_delta, beta_delta)
print("alpha : ", alpha)
print("beta : ", beta)

alpha :  0.08695652173913043
beta :  0.0


In [430]:
random_matrix = np.random.randint(2, size=(df_pca.shape[0], k)) # n x k 행렬 생성, 각 원소를 0 또는 1로 랜덤하게 초기화
print(random_matrix)
initU = np.array(random_matrix)  # initial U

[[1 1 0]
 [1 1 0]
 [1 0 1]
 [1 0 1]
 [1 0 0]
 [1 1 0]
 [1 0 1]
 [0 1 0]
 [0 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 1]
 [1 1 1]
 [0 0 1]
 [1 1 0]]


In [431]:
import numpy as np

def neo_kmeans(X, k, alpha, beta, initU):
    # NEO-K-Means (Non-exhaustive and Overlapping clustering)

    N = X.shape[0]   # no. of data points
    dim = X.shape[1]  # dimension
    U = initU.copy()  # initial U
    t = 0
    t_max = 200
    alphaN = int(round(alpha * N))
    betaN = int(round(beta * N))
    J = float('inf')
    oldJ = 0
    epsilon = 0
    J_track = []

    D = np.zeros((N, k))
    M = np.zeros((dim, k))

    while abs(oldJ - J) > epsilon and t <= t_max:
        oldJ = J
        J = 0

        for j in range(k):
            ind = U[:, j].astype(bool)
            M[:, j] = np.mean(X[ind, :], axis=0)

        for j in range(k):
            diff = X - np.tile(M[:, j], (N, 1))
            D[:, j] = np.sum(diff**2, axis=1)

        ind = np.argpartition(D, N - betaN, axis=None)[:N - betaN]
        ind_flat = np.unravel_index(ind, D.shape)
        sorted_d = D[ind_flat]
        sorted_n, sorted_k = ind_flat
        num_assign = N - betaN
        J += np.sum(sorted_d[:num_assign])
        U = np.zeros((N, k))
        U[sorted_n[:num_assign], sorted_k[:num_assign]] = 1
        D[sorted_n[:num_assign], sorted_k[:num_assign]] = np.inf

        n = 0
        while n < (alphaN + betaN):
            min_d = np.min(D)
            J += min_d
            i_star, j_star = np.unravel_index(np.argmin(D), D.shape)
            U[i_star, j_star] = 1
            D[i_star, j_star] = np.inf
            n += 1

        t += 1
        J_track.append(J)
        print(f'***** iteration: {t}, objective: {J:.6f}')

    print(f'***** No. of iterations done: {t}')

    # display results
    print(f'***** Total no. of data points: {N}')
    print(f'***** alpha: {alpha:.3f}, alphaN: {alphaN}')
    print(f'***** beta: {beta:.3f}, betaN: {betaN}')

    return U, J, J_track
U, J, J_track = neo_kmeans(df_pca, k, alpha, beta, initU)

***** iteration: 1, objective: 0.705657
***** iteration: 2, objective: 0.517414
***** iteration: 3, objective: 0.446503
***** iteration: 4, objective: 0.438675
***** iteration: 5, objective: 0.438675
***** No. of iterations done: 5
***** Total no. of data points: 23
***** alpha: 0.087, alphaN: 2
***** beta: 0.000, betaN: 0


In [432]:
x_clu = [int(x[0]) for x in U]
x_clu

[0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

In [ ]:
result_df = df[['Title', 'text']]
for i in range(k):
  result_df['C{}'.format(i+1)]= [int(x[i]) for x in U]

In [434]:
result_df

Title  \
0                             Hadoop Yarn 아키텍쳐   
1                         하둡 프로그래밍 - MapReduce   
2                         OpenSearch에 대해 알아보자!   
3                                 {일상} 10분만 일상   
4                                      Airflow   
5            [Apache Kafka] Kafka REST Proxy란?   
6                                        HBase   
7                                [데이터 처리] Hive   
8                            컴퓨터망 18) FTP TFTP   
9             SP - 8.1 Virtual Memory Concepts   
10                  [OS] POSIX message passing   
11                                   Deadlocks   
12                    [OS] Mutex and Semaphore   
13        [OS] H/W support for Synchronization   
14             [OS] System-V shared Memory API   
15                  [OS] 프로세서, 프로세스, 프로그램, 스레드   
16        [Algorithm] 깊이우선탐색(DFS)과 너비우선탐색(BFS)   
17                 [알고리즘] 다익스트라(Dijkstra) 알고리즘   
18     [알고리즘] 그리디, 탐욕 알고리즘 (Greedy Algorithm)    
19                            [자료구조] 트리 (Tree)   
20  [알고리즘] 벨만-포드 알고리즘 (Bellman-Ford Algorithm)   
21                 동적 계획법(Dynamic Programming)   
22                           [책 요약] 제텔카스텐 - 도입   

                                                 text  C1  C2  C3  
0   개발Hadoop을 배우게 되면, MapReduce 다음으로 Yarn의 개념을 가장 ...   0   0   0  
1   하둡하둡은 기본적으로 HDFS, MapReduce로 구성된다. 맵리듀스는 HDFS에...   0   0   0  
2   Opensearch는 Elastic Search가 기업화를 꾀하는데에 대한 반발로 ...   1   1   1  
3   {일상}10분동안 할게 뭐 있다고, 아둥바둥 힘들게 기록하나 싶다가도나한테 올바른 ...   1   1   1  
4   강의정리 - MLOps목차\nApache Airflow 소개\n-- Batch Pr...   1   1   1  
5   Kafka공식 문서REST Proxy 란?Confluent에서 제공하는 Apache...   1   1   1  
6   소프트웨어 아키텍처HBase아파치 HBase는 Hadoop을 위한 공개 NoSQL ...   1   1   0  
7   Data Engineering 기초등장 배경데이터를 처리하기 위해 사용하는 맵 리듀...   0   0   0  
8   컴퓨터네트워크18. File Transfer: FTP이 장에서는 파일 전송과 관련된...   1   1   1  
9   SystemProgramming  대망의 System Programming 연재 마...   0   0   1  
10  Operating system✅ msgget() - create a message ...   1   1   1  
11  운영체제우리 말로는 교착상태라고도 한다. \n위의 그림을 보면 사거리에서 차들이 각...   0   0   0  
12  Operating system지비씨 리눅스 과제할때 급하게 주워담은 지식으로 구현하...   0   0   0  
13  Operating system✅ Memory Model메모리 모델은 컴퓨터 아키텍처...   0   0   0  
14  Operating system이전 포스팅에서 설명한 IPC의 방법 중 하나인 Sha...   0   0   0  
15  Operating system용어정리✔️ 프로세서 (Processor)컴퓨터 운영을...   0   0   1  
16  Algorithm📌 깊이우선탐색(DFS)과 너비우선탐색(BFS)▶ 해당 개념을 알기...   0   0   0  
17  Data Structure & Algorithm1-1. 개요다익스트라(dijkstr...   0   0   0  
18  알고리즘Greedy : '탐욕스러운, 욕심 많은'이라는 뜻탐욕 알고리즘이란, 선택의...   0   0   0  
19  Datastructure사진의 출처 : 링크\n트리(Tree)는 그래프의 일종으로 ...   0   0   0  
20  Algorithm\n벨만-포드 알고리즘은 한 노드에서 다른 노드까지의 최단 거리를 ...   0   0   0  
21  알고리즘동적 계획법(Dynamic Programming, DP)은 큰 문제를 작은 ...   0   0   0  
22  그 누구도 글을 쓰지 않고는 생각할 수 없다. -니클라스 루만글쓰기가 힘든 이유는 ...   1   1   1